# Copyright 2020 RIFT Inc
# Copyright 2021 DZS Inc
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ingress-default-backend
  name: rw-haproxy-default-backend
  namespace: {{ .Values.global.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ingress-default-backend
  template:
    metadata:
      labels:
        run: ingress-default-backend
        release: {{ .Release.Name }}
    spec:
      {{- if and .Values.global.ensureSecurityContext (not (has "appHaproxyDefaultBackend" .Values.global.excludeAppsInSecurityContext)) }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: {{ .Values.defaultbackend.runAsUser }}
        runAsGroup: {{ .Values.global.defaultGroup }}
      {{- end }}
      imagePullSecrets:
        {{ if .Values.image.imagePullSecrets }}
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        {{ else }}
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
        {{- end }}
      containers:
        - name: ingress-default-backend
          image: {{ .Values.defaultbackend.image.repository -}} : {{- .Values.defaultbackend.image.tag }}
          imagePullPolicy: {{ .Values.defaultbackend.image.pullPolicy }}

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20

          ports:
            - containerPort: 8080


          {{- if and .Values.global.ensureSecurityContext (not (has "appHaproxyDefaultBackend" .Values.global.excludeAppsInSecurityContext)) }}
          securityContext:
            {{ toYaml .Values.global.partialSecurityContext | nindent 12 }}
            runAsUser: {{ .Values.defaultbackend.runAsUser }}
            runAsGroup: {{ .Values.global.defaultGroup }}
          {{- end }}

          {{- if and .Values.global.ensureResourceQuota (not (has "appHaproxyDefaultBackend" .Values.global.excludeAppsInResourceQuota)) }}
          {{- include "common.small" . | nindent 2 }}
          {{- end }}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
  namespace: {{ .Values.global.namespace.name }}
spec:
  selector:
    run: ingress-default-backend
  {{- if .Values.global.ipv6Mode }}
  ipFamilies:
  - IPv6
  {{- end }}
  ports:
  - name: port-1
    port: 8080
    protocol: TCP
    targetPort: 8080
