apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdnc-connector.fullname" . }}
  namespace: {{ include "sdnc.namespace" . }}
  labels:
    {{- include "sdnc-connector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "sdnc-connector.selectorLabels" . | nindent 4 }}
