{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sdnc-connector.serviceAccountName" . }}
  namespace: {{ include "sdnc.namespace" . }}
  labels:
    {{- include "sdnc-connector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
