apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    app: rw.sftp
{{- if .Values.service.annotations }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 22
      name: ssh
  selector:
    app: rw.sftp
