{{- if and .Values.openWebui.env.oauth.enabled .Values.openWebui.env.oauth.clientSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.openWebui.env.oauth.clientSecret.name }}
  namespace: {{ .Values.global.namespace.name }}
  labels:
    {{- include "llm-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.openWebui.env.oauth.clientSecret.key }}: {{ .Values.openWebui.env.oauth.clientSecret.value | quote }}
{{- end }}