# Copyright 2022 DZSInc
{{- if .Values.global.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "aeo.namespace" . }}
  labels:
    {{- include "aeo.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.global.aeoNamespacePrefix }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "aeo.namespace" . }}
  name: rift-edit
rules:
# core group edit permissions
- apiGroups: [""]
  resources: ["pods","configmaps", "secrets", "services"]
  verbs: ["get", "watch", "list", "create", "patch", "update", "delete", "deletecollection"]
# core group logs/status read permission
- apiGroups: [""]
  resources: ["pods/log","pods/status"]
  verbs: ["get", "watch", "list"]
# core group for pod/exec permission
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
# apps group edit permission
- apiGroups: ["apps"]
  resources: ["daemonsets","deployments", "replicasets", "statefulsets"]
  verbs: ["get", "watch", "list", "create", "patch", "update", "delete", "deletecollection"]
---
# Role binding for the default role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.namespace.name }}-role-bind
  namespace: {{ include "aeo.namespace" . }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ include "aeo.namespace" . }}
roleRef:
  kind: Role
  name: rift-edit
  apiGroup: rbac.authorization.k8s.io
{{- end }}
