#
# Copyright 2022 DZS Inc
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rw-aeo-tmf-server
  namespace: {{ include "aeo.namespace" . }}
  labels:
    app: rw.aeo.tmf
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: rw.aeo.tmf
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: 'metrics'
        prometheus.io/port: '9021'
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: rw.aeo.tmf
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      initContainers:
        - name: wait-for-deps
          image: "{{ .Values.initContainer.waitForDep.image.repository }}:{{ .Values.initContainer.waitForDep.image.tag }}"
          imagePullPolicy: {{ .Values.initContainer.waitForDep.image.pullPolicy }}
          env:
            - name: RW_NATS_SVC_NAME
              value: {{ include "nats.fqdn" . }}
            - name: RW_MONGODB_SVC_NAME
              value: {{ include "mongodb.fqdn" . }}
            - name: RW_REDIS_SVC_NAME
              value: {{ include "redis.fullname" . -}}.{{- .Values.global.namespace.name }}
            - name: RW_PROMETHEUS_SVC_NAME
              value: {{ include "prometheus.fullname" . -}}.{{- .Values.global.namespace.name }}
          command:
            - /wait-for
          args:
            - --host="$(RW_NATS_SVC_NAME):4222"
            - --host="$(RW_MONGODB_SVC_NAME):8006"
            - --host="$(RW_REDIS_SVC_NAME):8012"
            - --host="$(RW_PROMETHEUS_SVC_NAME):9090"
            - --timeout=120s
            - --verbose

      containers:
        - name: tmf-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.tmfServer.repository }}:{{ .Values.image.tmfServer.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.tmfServer.pullPolicy }}
          command: ["/usr/rift/rift-shell", "-i", "/", "--", "python3", "/usr/rift/usr/bin/service_app.py"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: RW_REDIS_SVC_NAME
            value: {{ include "redis.fullname" . -}}.{{- .Values.global.namespace.name }}
          - name: RW_NATS_SVC_NAME
            value: {{ include "nats.fullname" . -}}.{{- .Values.global.namespace.name }}
          - name: RW_K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 9021
            name: tmf-server

          volumeMounts:
          {{- with .Values.devSetup }}
          - name: localdisk
            mountPath: /localdisk
            readOnly: false
          - name: rift-install
            mountPath: /usr/rift
            readOnly: false
          {{- end }}

      nodeSelector:
        {{ if .Values.nodeSelector }}
        {{- toYaml .Values.nodeSelector | nindent 8 }}
        {{ end }}

      volumes:
      {{- with .Values.devSetup }}
        - name: localdisk
          hostPath:
            path: /localdisk
            type: Directory
        - name: rift-install
          hostPath:
            path: {{ .riftInstall }}
            type: Directory
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
