apiVersion: v1
kind: Secret
metadata:
  name: dzs-secret
  namespace: {{ .Values.global.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"docker.io\":{\"username\":\"dzscloudadmin\",\"password\":\"%s\",\"email\":\"noreply@zhone.com\",\"auth\":\"%s\"}}}" (env "DOCKERHUB_TOKEN") (printf "%s:%s" "dzscloudadmin" (env "DOCKERHUB_TOKEN") | b64enc) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: {{ .Values.global.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"docker.io\":{\"username\":\"dzscloudadmin\",\"password\":\"%s\",\"email\":\"noreply@zhone.com\",\"auth\":\"%s\"}}}" (env "DOCKERHUB_TOKEN") (printf "%s:%s" "dzscloudadmin" (env "DOCKERHUB_TOKEN") | b64enc) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dzs-secret
  namespace: aeo-{{ .Values.global.namespace.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"docker.io\":{\"username\":\"dzscloudadmin\",\"password\":\"%s\",\"email\":\"noreply@zhone.com\",\"auth\":\"%s\"}}}" (env "DOCKERHUB_TOKEN") (printf "%s:%s" "dzscloudadmin" (env "DOCKERHUB_TOKEN") | b64enc) | b64enc }}