apiVersion: v1

metadata:
  name: {{ include "netconf-device.fullname" . }}
  namespace: {{ include "sdnc.namespace" . }}
kind: ConfigMap

data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="WARN" monitorInterval="30">
        <Properties>
            <Property name="LOG_PATTERN">%d{ISO8601} | %-5p | dzsi | netconf | %t | %c{1} | %m%n</Property>
            <Property name="APP_LOG_ROOT">./logs</Property>
        </Properties>
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT" follow="true">
                <PatternLayout pattern="${LOG_PATTERN}" />
            </Console>
            <RollingFile name="appLog"
                         fileName="${APP_LOG_ROOT}/netconf-device.log"
                         filePattern="${APP_LOG_ROOT}/netconf-device-%d{yyyy-MM-dd}-%i.log">
                <PatternLayout pattern="${LOG_PATTERN}" />
                <Policies>
                    <SizeBasedTriggeringPolicy size="19500KB" />
                </Policies>
                <DefaultRolloverStrategy max="1" />
            </RollingFile>
        </Appenders>
        <Loggers>
            <Root level="info">
                <AppenderRef ref="Console" />
                <AppenderRef ref="appLog" />
            </Root>
        </Loggers>
    </Configuration>

  serverconfig.json: |
    {{ .Values.serverconfig.json }}

  {{- range $data := .Values.serverconfig.datastore.configuration }}
  {{ .name }}: |
{{ .data | indent 4 }}
  {{- end }}

  {{- range $data := .Values.serverconfig.datastore.operational }}
  {{ .name }}: |
{{ .data | indent 4 }}
  {{- end }}
