apiVersion: v1
kind: Service
metadata:
  name: {{ include "netconf-device.fullname" . }}
  namespace: {{ include "sdnc.namespace" . }}
  labels:
    {{- include "netconf-device.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.serverconfig.servers }}
    - port: {{ . }}
      targetPort: ssh{{ . }}
      protocol: TCP
      name: ssh{{ . }}
    {{- end}}
  selector:
    {{- include "netconf-device.selectorLabels" . | nindent 4 }}
