apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "smi-database"
  namespace: {{ include "explore.namespace" . }}
spec:
  defaults:
    replicasUseFQDN: "no"
    templates:
        podTemplate: pod-template-with-volumes
        dataVolumeClaimTemplate: data-storage-vc-template
        logVolumeClaimTemplate: log-storage-vc-template
        serviceTemplate: chi-service-template

  configuration:
    users:
      demo/default: demo
      demo/password: demo
      demo/profile: default
      demo/quota: default
      demo/networks/ip: "::/0"
    clusters:
      - name: "smi-database"
        templates:
          podTemplate: pod-template-with-volumes
        layout:
          shardsCount: 1
          replicasCount: 1

  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              image: {{ .Values.chiDb.image.repository }}:{{ .Values.chiDb.image.tag }}
              volumeMounts:
                - name: data-storage-vc-template
                  mountPath: /var/lib/clickhouse
                - name: log-storage-vc-template
                  mountPath: /var/log/clickhouse-server

    volumeClaimTemplates:
      - name: data-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
      - name: log-storage-vc-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

    serviceTemplates:
      - name: chi-service-template
        generateName: "{{ tpl .Values.chiDb.service.name . }}"
        spec:
          ports:
            - name: http
              port: {{ tpl (.Values.chiDb.service.httpPort | quote) . | replace "\"" "" }}
            - name: client
              port: {{ tpl (.Values.chiDb.service.port | quote) . | replace "\"" "" }}
          type: {{ tpl .Values.chiDb.service.type . }}
