{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.namespace.name }}-strimzi-cluster-operator-leader-election
  namespace: {{ .Values.global.namespace.name }}
  labels:
    app: {{ template "strimzi.name" . }}
    chart: {{ template "strimzi.chart" . }}
    component: role-binding
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount }}
    namespace: {{ .Values.global.namespace.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.namespace.name }}-strimzi-cluster-operator-leader-election
  apiGroup: rbac.authorization.k8s.io
{{- end }}
