{{- if and .Values.rbac.create .Values.createGlobalResources -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.global.namespace.name }}-strimzi-cluster-operator-kafka-broker-delegation
  labels:
    app: {{ template "strimzi.name" . }}
    chart: {{ template "strimzi.chart" . }}
    component: broker-role-binding
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
# The Kafka broker cluster role must be bound to the cluster operator service account so that it can delegate the cluster role to the Kafka brokers.
# This must be done to avoid escalating privileges which would be blocked by Kubernetes.
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount }}
    namespace: {{ .Values.global.namespace.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.global.namespace.name }}-strimzi-kafka-broker
  apiGroup: rbac.authorization.k8s.io

{{- end -}}
