apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka.prefix" . }}
  namespace: {{  .Values.global.namespace.name }}
  labels:
    strimzi.io/cluster: {{ include "kafka.prefix" . }}
spec:
  kafka:
    version: 4.1.0
    replicas: 1
    metadataVersion: "4.1"
    #    authorization:
    #  type: simple
    #  superUsers:
    #    - User:ANONYMOUS
    #    - User:anonymous  
    config:
      auto.create.topics.enable: true
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      group.initial.rebalance.delay.ms: 250
      log.retention.ms: 86400000
      log.segment.bytes: 134217728
      log.retention.bytes: 1073741824
      # sasl.enabled.mechanisms: SCRAM-SHA-512
      #sasl.mechanism.inter.broker.protocol: SCRAM-SHA-512
    logging:
       type: inline
       loggers:
          # Kafka 4.0+ uses Log4j2
          rootLogger.level: INFO
    listeners:
       - name: plain
         port: 9092
         type: internal
         tls: false
         configuration:
             useServiceDnsDomain: true
       - name: tls
         port: 9093
         type: internal
         tls: true
         authentication:
             type: tls
       - name: external
         port: 9094
         type: cluster-ip
         tls: true
         configuration:
           brokers:
             - broker: 0
               advertisedHost: {{ .Values.global.ingress.externalAddress | default "127.0.0.1" }}
               advertisedPort: 9094
         authentication:
             type: scram-sha-512
    livenessProbe:
       initialDelaySeconds: 15
       timeoutSeconds: 5
    readinessProbe:
       initialDelaySeconds: 15
       timeoutSeconds: 5
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 5Gi
          kraftMetadata: shared
          deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}


