apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .Values.kafkaTopics.sdnc.alarm }}
  namespace: {{  .Values.global.namespace.name }}
  labels:
    strimzi.io/cluster: {{ include "kafka.prefix" . }}
spec:
  topicName: zhone.sdnc.alarm      
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000 
    segment.bytes: 134217728
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .Values.kafkaTopics.sdnc.pm }}
  namespace: {{  .Values.global.namespace.name }}
  labels:
    strimzi.io/cluster: {{ include "kafka.prefix" . }}
spec:
  topicName: zhone.sdnc.pm    
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000
    segment.bytes: 134217728
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .Values.kafkaTopics.sdnc.tca }}
  namespace: {{  .Values.global.namespace.name }}
  labels:
    strimzi.io/cluster: {{ include "kafka.prefix" . }}
spec:
  topicName: zhone.sdnc.tca      
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000
    segment.bytes: 134217728
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: {{ .Values.kafkaTopics.sdnc.onu }}
  namespace: {{  .Values.global.namespace.name }}
  labels:
    strimzi.io/cluster: {{ include "kafka.prefix" . }}
spec:
  topicName: zhone.sdnc.onu-presence     
  partitions: 1
  replicas: 1
  config:
    retention.ms: 86400000
    segment.bytes: 134217728
