apiVersion: v1
kind: Secret
metadata:
  name: kafka-user-admin-secret
  namespace: {{  .Values.global.namespace.name }}
type: Opaque
stringData:
  password: {{ .Values.kafkaUser.pwd }} 

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-user-superadmin-secret
  namespace: {{  .Values.global.namespace.name }}
type: Opaque
stringData:
  password: {{ .Values.kafkaSuperUser.pwd }}

