{
 "title": "RW.AEO TMF Server Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Request Rate(RPS)",
   "type": "stat",
   "description": "Request rate for tmf server over period of 10 minute.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(rw_aeo_tmf_request_latency_ms_count[10m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Request Latency (ms)",
   "type": "stat",
   "description": "Average request latency for tmf server",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(rw_aeo_tmf_request_latency_ms_sum[10m]))  by (pod) / sum (rate(rw_aeo_tmf_request_latency_ms_count[10m]))  by (pod) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Requests Processed",
   "type": "bargauge",
   "description": "Total requests processed by tmf server Includes success and failure",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rw_aeo_tmf_request_latency_ms_count) by (method, pod)",
     "legendFormat": "{{method, pod}}"
    }
   ]
  },
  {
   "title": "5xx/4xx Error Response Rate",
   "type": "timeseries",
   "description": "Rate at which requests are getting sent with HTTP status code 5xx or 4xx",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum (rate(rw_aeo_tmf_request_latency_ms_count{code=~\"5.*|4.*\"}[10m])) by (code, pod, handler)",
     "legendFormat": "{{code}}, {{pod}}, {{handler}} "
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "bargauge",
   "description": "Total requests per handler",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rw_aeo_tmf_request_latency_ms_count) by (handler, pod)",
     "legendFormat": "{{handler, pod}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "Request rate for tmf server. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum (rate (rw_aeo_tmf_request_latency_ms_count[10m])) by (pod, handler)",
     "legendFormat": "{{pod, handler}}"
    }
   ]
  },
  {
   "title": "Request Latency (ms)",
   "type": "timeseries",
   "description": "Average request latency by method",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum (rate(rw_aeo_tmf_request_latency_ms_sum[10m])) by (pod, handler) / sum (rate(rw_aeo_tmf_request_latency_ms_count[10m])) by (pod, handler)",
     "legendFormat": "{{pod, handler}}"
    }
   ]
  }
 ]
}