{
 "title": "RW.AEO Application Metrics (Resource Level)",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Resource Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Configured SDN Controller Counts by Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (project) (rw_aeo_sdnc_account_count{container=\"resource-controller\", job=\"aeo-metrics\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Count of Resource Class Usage by Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (project) (rw_aeo_resource_class_count{container=\"resource-controller\", job=\"aeo-metrics\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Resource Profiles Increase Rate by Project and Type",
   "type": "timeseries",
   "description": "This is over 5 mins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (project, type) (rate(rw_aeo_resource_profiles_total{container=\"resource-controller\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "Project: {{project}}, Type: {{type}}"
    }
   ]
  },
  {
   "title": "Resource Profiles Increase Count by Project and Type",
   "type": "stat",
   "description": "This is over the observation period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by (project, type) (increase(rw_aeo_resource_profiles_total{container=\"resource-controller\", job=\"aeo-metrics\"}[$__range])))",
     "legendFormat": "Project: {{project}}, Type: {{type}}"
    }
   ]
  },
  { "title": "Resource Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Rate of Executed Resource Operations by Project",
   "type": "timeseries",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_aeo_exec_resource_op_total{container=\"resource-worker\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "SDN Notifications Rate per Project",
   "type": "timeseries",
   "description": "over Observation Period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_aeo_sdn_notification_total{container=\"resource-worker\", job=\"aeo-metrics\"}[5m]))"
    }
   ]
  },
  {
   "title": "Average Resource Operations Function Execution Time by Pod",
   "type": "timeseries",
   "description": "function name doesn't have to correspond to an actual function - it can be for a block of code, etc.\nMeant to be a unique identifying name for a task",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg by (pod) (rw_aeo_resource_worker_function_times_seconds{container=\"resource-worker\", function_name=\"exec_resource_op\", job=\"aeo-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Function Execution Time for SDNC Validation by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "avg by (pod) (rw_aeo_resource_worker_function_times_seconds{container=\"resource-worker\", function_name=\"validate_sdnc_account\", job=\"aeo-metrics\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "SDNC Accounts Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (project) (rw_aeo_dzs_sdnc_accounts{container=\"resource-worker\", job=\"aeo-metrics\"})"
    }
   ]
  },
  {
   "title": "Rate of Internal Errors in SDN Notification Listener",
   "type": "timeseries",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum by (project) (rate(rw_aeo_resource_worker_errors_total{container=\"resource-worker\", error_type=\"internal\", function=\"kafka_listeners\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Internal Errors in Executing Resource Operations",
   "type": "timeseries",
   "description": "over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (project) (rate(rw_aeo_resource_worker_errors_total{container=\"resource-worker\", error_type=\"internal\", function=\"exec_resource_op\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Internal Errors in SDNC Account Validation",
   "type": "timeseries",
   "description": "over 5 minutes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (project) (rate(rw_aeo_resource_worker_errors_total{container=\"resource-worker\", error_type=\"internal\", function=\"validate_sdnc_account\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}