{
 "title": "RW.AEO Cluster Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Service Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Online Workers Count",
   "type": "graph",
   "description": "Workers Registered with the Controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_manager_online_workers{container=\"service-controller\", job=\"aeo-metrics\"})",
     "legendFormat": "No of Workers"
    }
   ]
  },
  {
   "title": "Worker Pods Running",
   "type": "graph",
   "description": "Worker Pods actually running in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (type) (rw_process_cpu_utilization{container=\"service-worker\", type=\"threads\", job=\"aeo-metrics\"})",
     "legendFormat": "No of Workers"
    }
   ]
  },
  {
   "title": "Job Assignment Rate",
   "type": "graph",
   "description": "Job success and ressaignments averaged over 5 mins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rw_manager_job_assgn_counter_total{container=\"service-controller\", type!=\"worker-not-found\", job=\"aeo-metrics\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Workers Not Found Rate",
   "type": "graph",
   "description": "Increase in count of worker-not-found while assigning jobs averaged over 5m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rw_manager_job_assgn_counter_total{container=\"service-controller\",type=\"worker-not-found\", job=\"aeo-metrics\"}[5m])"
    }
   ]
  },
  {
   "title": "Online Status Change Rate",
   "type": "graph",
   "description": "Rate of workers added or removed online averaged over 5m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rw_manager_scheduler_stats_total{container=\"service-controller\",type!=\"audit-failure-count\", job=\"aeo-metrics\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Audit Failure Rate",
   "type": "graph",
   "description": "Rate of increase in failed worker audits averaged over 5m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rw_manager_scheduler_stats_total{container=\"service-controller\",type=\"add-online-count\", job=\"aeo-metrics\"}[5m])"
    }
   ]
  },
  {
   "title": "Service Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Occupancy Percentage per Pod",
   "type": "graph",
   "description": "Percentage of jobs in queue against the queue size.\nUpper and lower watermarks indicate limits palced in settings",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_worker_queue{container=\"service-worker\",type=\"queue_current_size\", job=\"aeo-metrics\"}/scalar(rw_worker_queue{container=\"service-worker\",type=\"queue_max_size\", job=\"aeo-metrics\"})*100)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(rw_worker_env_cfg{container=\"service-worker\",type=\"lwm_percent\", pod=\"rw-aeo-service-worker-0\", job=\"aeo-metrics\"})",
     "legendFormat": "Low Watermark"
    },
    {
     "expr": "avg(rw_worker_env_cfg{container=\"service-worker\",type=\"hwm_percent\", pod=\"rw-aeo-service-worker-0\", job=\"aeo-metrics\"})",
     "legendFormat": "High Watermark"
    }
   ]
  },
  {
   "title": "Asynchronous Threads",
   "type": "stat",
   "description": "Same for each pod",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rw_worker_env_cfg{container=\"service-worker\", type=\"asyncio_threads\", pod=\"rw-aeo-service-worker-0\", job=\"aeo-metrics\"})"
    }
   ]
  },
  {
   "title": "Flow Control Tasks",
   "type": "stat",
   "description": "same for each pod",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rw_worker_env_cfg{container=\"service-worker\", type=\"fc_tasks_num\",pod=\"rw-aeo-service-worker-0\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Periods Secs",
   "type": "stat",
   "description": "same for each pod",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rw_worker_env_cfg{container=\"service-worker\", type=\"period_secs\",pod=\"rw-aeo-service-worker-0\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Jobs in Processing State per Pod",
   "type": "graph",
   "description": "No. of Jobs currently being processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_worker_queue{container=\"service-worker\",type=\"processing\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Jobs Finished per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(rw_worker_counters_total{container=\"service-worker\", type=\"finished\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Jobs Claimed per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(rw_worker_counters_total{container=\"service-worker\", type =\"claimed\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of High Water Mark Crossed per Pod",
   "type": "graph",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(rw_worker_counters_total{container=\"service-worker\",type=\"hwm_crossed\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Low Water Mark Crossed per Pod",
   "type": "graph",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(rw_worker_counters_total{container=\"service-worker\",type=\"lwm_crossed\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker State",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rw_worker_state{container=\"service-worker\", job=\"aeo-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resource Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job Assignment Results Rate",
   "type": "graph",
   "description": "Averaged over 5 mins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rw_manager_job_assgn_counter_total{container=\"resource-controller\", type!=\"worker-not-found\", job=\"aeo-metrics\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Workers Not Found Rate",
   "type": "graph",
   "description": "Increase in count of worker-not-found while assigning jobs averaged over 5m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rw_manager_job_assgn_counter_total{container=\"resource-controller\",type=\"worker-not-found\", job=\"aeo-metrics\"}[5m])"
    }
   ]
  },
  {
   "title": "Online Status Change Rate",
   "type": "graph",
   "description": "Rate of workers added or removed online averaged over 5m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rw_manager_scheduler_stats_total{container=\"resource-controller\",type!=\"audit-failure-count\", job=\"aeo-metrics\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Audit Failure Rate",
   "type": "graph",
   "description": "Rate of increase in failed worker audits averaged over 5m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rw_manager_scheduler_stats_total{container=\"resource-controller\",type=\"add-online-count\", job=\"aeo-metrics\"}[5m])"
    }
   ]
  },
  {
   "title": "Resource Workers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Occupancy Percentage per Pod",
   "type": "graph",
   "description": "Percentage of jobs in queue against the queue size.\nUpper and lower watermarks indicate limits palced in settings",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_worker_queue{container=\"resource-worker\",type=\"queue_current_size\", job=\"aeo-metrics\"}/scalar(rw_worker_queue{container=\"resource-worker\",type=\"queue_max_size\", job=\"aeo-metrics\"})*100)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "avg(rw_worker_env_cfg{container=\"resource-worker\",type=\"lwm_percent\", pod=\"rw-aeo-resource-worker-0\", job=\"aeo-metrics\"})",
     "legendFormat": "Low Watermark"
    },
    {
     "expr": "avg(rw_worker_env_cfg{container=\"resource-worker\",type=\"hwm_percent\", pod=\"rw-aeo-resource-worker-0\", job=\"aeo-metrics\"})",
     "legendFormat": "High Watermark"
    }
   ]
  },
  {
   "title": "Asynchronous Threads",
   "type": "stat",
   "description": "Same for each pod",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rw_worker_env_cfg{container=\"resource-worker\", type=\"asyncio_threads\", pod=\"rw-aeo-resource-worker-0\", job=\"aeo-metrics\"})"
    }
   ]
  },
  {
   "title": "Flow Control Tasks",
   "type": "stat",
   "description": "same for each pod",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rw_worker_env_cfg{container=\"resource-worker\", type=\"fc_tasks_num\",pod=\"rw-aeo-resource-worker-0\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Periods Secs",
   "type": "stat",
   "description": "same for each pod",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rw_worker_env_cfg{container=\"resource-worker\", type=\"period_secs\",pod=\"rw-aeo-resource-worker-0\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Jobs in Processing State per Pod",
   "type": "graph",
   "description": "No. of Jobs currently being processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_worker_queue{container=\"resource-worker\",type=\"processing\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Jobs Finished per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(rw_worker_counters_total{container=\"resource-worker\", type=\"finished\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Jobs Claimed per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(rw_worker_counters_total{container=\"resource-worker\", type =\"claimed\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of High Water Mark Crossed per Pod",
   "type": "graph",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(rw_worker_counters_total{container=\"resource-worker\",type=\"hwm_crossed\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Low Water Mark Crossed per Pod",
   "type": "graph",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (irate(rw_worker_counters_total{container=\"resource-worker\",type=\"lwm_crossed\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Worker State",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "rw_worker_state{container=\"resource-worker\", job=\"aeo-metrics\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}