{
 "title": "RW.AEO System Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Service Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_process_cpu_utilization{type=\"total_utilization\", pod=\"rw-aeo-controller-0\",container=\"service-controller\",job=\"aeo-metrics\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Node (User) CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_process_cpu_utilization{type=\"total_utilization_node_user\", pod=\"rw-aeo-controller-0\",container=\"service-controller\", job=\"aeo-metrics\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Node (System) CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_process_cpu_utilization{type=\"total_utilization_node_system\", pod=\"rw-aeo-controller-0\",container=\"service-controller\", job=\"aeo-metrics\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Number of Threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_process_cpu_utilization{type=\"threads\", pod=\"rw-aeo-controller-0\",container=\"service-controller\", job=\"aeo-metrics\"}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"service-controller\", type=\"rss\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percentage RSS memory used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_process_memory{container=\"service-controller\", type=\"rss\"}/scalar(rw_process_memory{container=\"service-controller\", type=\"max\", job=\"aeo-metrics\"})*100",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "USS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"service-controller\", type=\"uss\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "VMZ Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"service-controller\", type=\"vms\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collector: Collection Rate",
   "type": "graph",
   "description": "Rate of total items collected by garbage collector every 10 mins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (generation) (irate(python_gc_objects_collected_total{container=\"service-controller\", job=\"aeo-metrics\"}[10m]))",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Garbage Collector: Uncollectable Items Rate",
   "type": "graph",
   "description": "Total rate of increase in items that cannot be collected by garbage collector over 10 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (generation) (irate(python_gc_objects_uncollectable_total{container=\"service-controller\", job=\"aeo-metrics\"}[10m]))",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (process_open_fds{job=\"aeo-metrics\", container=\"service-controller\"})"
    }
   ]
  },
  {
   "title": "Service Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current No. of Workers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (type) (rw_process_cpu_utilization{container=\"service-worker\", type=\"threads\", job=\"aeo-metrics\"})"
    }
   ]
  },
  {
   "title": "No. of Workers Trend",
   "type": "graph",
   "description": "Shows the trend of no. of workers currently running",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (type) (rw_process_cpu_utilization{container=\"service-worker\", type=\"threads\", job=\"aeo-metrics\"})",
     "legendFormat": "worker count"
    }
   ]
  },
  {
   "title": "No. of Threads per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_cpu_utilization{type=\"threads\",container=\"service-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process CPU Utilization per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_cpu_utilization{type=\"total_utilization\", container=\"service-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node CPU Utilization (User) per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_cpu_utilization{type=\"total_utilization_node_user\", container=\"service-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node CPU Utilization (System) per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_cpu_utilization{type=\"total_utilization_node_system\", container=\"service-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"service-worker\", type=\"rss\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS Memory Utilization per Pod (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rw_process_memory{container=\"service-worker\", type=\"rss\", job=\"aeo-metrics\"}) by (pod)/sum(rw_process_memory{container=\"service-worker\", type=\"max\", job=\"aeo-metrics\"}) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "USS Memory Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"service-worker\", type=\"uss\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "VMZ Memory Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"service-worker\", type=\"vms\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collector: Collected Objects Rate",
   "type": "graph",
   "description": "Increase in items collected by garbage collector every 5 minutes per pod per generation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, generation) (irate(python_gc_objects_collected_total{container=\"service-worker\", job=\"aeo-metrics\"}[10m]))",
     "legendFormat": "Generation {{generation}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collector: Uncollectable Objects Rate",
   "type": "graph",
   "description": "Increase in items that cannot be collected by garbage collector every 5 minutes per pod and generation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, generation) (irate(python_gc_objects_uncollectable_total{container=\"service-worker\", job=\"aeo-metrics\"}[10m]))",
     "legendFormat": "Generation {{generation}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (process_open_fds{job=\"aeo-metrics\", container=\"service-worker\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resource Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_process_cpu_utilization{type=\"total_utilization\", pod=\"rw-aeo-controller-0\",container=\"resource-controller\", job=\"aeo-metrics\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Node (User) CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_process_cpu_utilization{type=\"total_utilization_node_user\", pod=\"rw-aeo-controller-0\",container=\"resource-controller\", job=\"aeo-metrics\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Node (System) CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_process_cpu_utilization{type=\"total_utilization_node_system\", pod=\"rw-aeo-controller-0\",container=\"resource-controller\", job=\"aeo-metrics\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Number of Threads Used",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rw_process_cpu_utilization{type=\"threads\", pod=\"rw-aeo-controller-0\",container=\"resource-controller\", job=\"aeo-metrics\"}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"resource-controller\", type=\"rss\", job=\"aeo-metrics\"})"
    }
   ]
  },
  {
   "title": "Percentage RSS memory used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rw_process_memory{container=\"resource-controller\", type=\"rss\", job=\"aeo-metrics\"}/scalar(rw_process_memory{container=\"resource-controller\", type=\"max\", job=\"aeo-metrics\"})*100",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "USS Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"resource-controller\", type=\"uss\", job=\"aeo-metrics\"})"
    }
   ]
  },
  {
   "title": "VMZ Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"resource-controller\", type=\"vms\", job=\"aeo-metrics\"})"
    }
   ]
  },
  {
   "title": "Garbage Collector: Collection Rate",
   "type": "graph",
   "description": "Object collection rate by garbage collector over 10 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, generation) (irate(python_gc_objects_collected_total{container=\"resource-controller\", job=\"aeo-metrics\"}[10m]))",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Garbage Collector: Uncollectable Items Rate",
   "type": "graph",
   "description": "Rate of increase of uncollectable objects in garbage collector by generation (averaged to 10 m)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, generation) (irate(python_gc_objects_uncollectable_total{container=\"resource-controller\", job=\"aeo-metrics\"}[10m]))",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (process_open_fds{job=\"aeo-metrics\", container=\"resource-controller\"})"
    }
   ]
  },
  {
   "title": "Resource Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current No. of Workers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 122 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (type) (rw_process_cpu_utilization{type=\"threads\", container=\"resource-worker\", job=\"aeo-metrics\"})"
    }
   ]
  },
  {
   "title": "No of Workers Trend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (type) (rw_process_cpu_utilization{container=\"resource-worker\", type=\"threads\", job=\"aeo-metrics\"})",
     "legendFormat": "worker count"
    }
   ]
  },
  {
   "title": "No. of Threads per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_cpu_utilization{type=\"threads\",container=\"resource-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Process CPU Utilization per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_cpu_utilization{type=\"total_utilization\", container=\"resource-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node CPU Utilization (User) per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rw_process_cpu_utilization{type=\"total_utilization_node_user\", container=\"resource-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node CPU Utilization (System) per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_cpu_utilization{type=\"total_utilization_node_system\", container=\"resource-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"resource-worker\", type=\"rss\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RSS Memory Utilization per Pod (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rw_process_memory{container=\"resource-worker\", type=\"rss\", job=\"aeo-metrics\"}) by (pod)/sum(rw_process_memory{container=\"resource-worker\", type=\"max\", job=\"aeo-metrics\"}) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "USS Memory Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"resource-worker\", type=\"uss\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "VMZ Memory Usage per Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rw_process_memory{container=\"resource-worker\", type=\"vms\", job=\"aeo-metrics\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collector: Collected Objects Rate",
   "type": "graph",
   "description": "Increase in items collected by garbage collector every 5 minutes per pod per generation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, generation) (irate(python_gc_objects_collected_total{container=\"resource-worker\", job=\"aeo-metrics\"}[10m]))",
     "legendFormat": "Generation {{generation}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Garbage Collector: Uncollectable Objects Rate",
   "type": "graph",
   "description": "Increase in items that cannot be collected by garbage collector every 5 minutes per pod and generation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, generation) (irate(python_gc_objects_uncollectable_total{container=\"resource-worker\", job=\"aeo-metrics\"}[10m]))",
     "legendFormat": "Generation {{generation}}, {{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (process_open_fds{job=\"aeo-metrics\", container=\"resource-worker\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}