{
 "title": "RW.AEO Application Metrics (Service Orders)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate of Orders By Type",
   "type": "timeseries",
   "description": "Create and Delete orders over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (request_type) (irate(rw_service_order_request_total{container=\"service-controller\",product=\"aeo\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Total Creation Orders over Observation Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by (container) (increase(rw_service_order_request_total{container=\"service-controller\",product=\"aeo\",request_type=\"create\", job=\"aeo-metrics\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delete Orders over Observation Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by (container)(increase(rw_service_order_request_total{container=\"service-controller\",product=\"aeo\",request_type=\"delete\", job=\"aeo-metrics\"}[$__range])))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Configured Service Spec Count",
   "type": "timeseries",
   "description": "Service specification configured in the system",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (project, type) (rw_service_spec_count{product=\"aeo\",container=\"service-controller\", job=\"aeo-metrics\"})",
     "legendFormat": "Project: {{project}}, Type: {{type}}"
    }
   ]
  },
  {
   "title": "Order Latency",
   "type": "timeseries",
   "description": "Service order RPC latency in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (request_type) (rw_service_order_manager_latency{container=\"service-controller\", product=\"aeo\", job=\"aeo-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Service Order Flow Tasks by Project",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (project) (rw_service_worker_flow_tasks{container=\"service-worker\", job=\"aeo-metrics\"})",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Total Created Orders over Observation Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by (container)(increase(rw_service_worker_orders_total{container=\"service-worker\",type=\"created\", job=\"aeo-metrics\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Deleted Orders over Observation Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by (container)(increase(rw_service_worker_orders_total{container=\"service-worker\",type=\"deleted\", job=\"aeo-metrics\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Created Orders Rate by Project",
   "type": "timeseries",
   "description": "Over 5 minute period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_service_worker_orders_total{container=\"service-worker\",type=\"created\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Deleted Orders Rate by Project",
   "type": "timeseries",
   "description": "Over 5 minute period",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_service_worker_orders_total{container=\"service-worker\",type=\"deleted\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Successful Order Creation Rate per Project",
   "type": "timeseries",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_service_worker_results_total{order_type=\"create\",result_type=\"success\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Order Creation Rate per Project",
   "type": "timeseries",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_service_worker_results_total{container=\"service-worker\",order_type=\"create\",result_type=\"failed\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Successful Order Deletion Rate per Project",
   "type": "timeseries",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_service_worker_results_total{container=\"service-worker\",order_type=\"delete\",result_type=\"success\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Failed Order Deletion Rate per Project",
   "type": "timeseries",
   "description": "over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_service_worker_results_total{container=\"service-worker\",order_type=\"delete\",result_type=\"failed\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Timeout Error Rate by Project",
   "type": "timeseries",
   "description": "Over 5 minutres",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_service_worker_task_errors_total{container=\"service-worker\",type=\"timeout\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "Project: {{project}}"
    }
   ]
  },
  {
   "title": "Internal Error Rate by Project",
   "type": "timeseries",
   "description": "Over 5 minutres",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (project) (irate(rw_service_worker_task_errors_total{container=\"service-worker\",type=\"internal\", job=\"aeo-metrics\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Timeout Errors over Observation Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (increase(rw_service_worker_task_errors_total{container=\"service-worker\",type=\"timeout\", job=\"aeo-metrics\"}[$__range]))",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Total Internal Errors over Observation Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum by (container) (increase(rw_service_worker_task_errors_total{container=\"service-worker\",type=\"internal\", job=\"aeo-metrics\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}