{
 "title": "Replicator Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Source Event Count Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(replicator_source_event_count{container=\"replicator\"}[5m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Target event count rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(replicator_target_event_count{container=\"replicator\"}[5m])",
     "legendFormat": "{{target}} - {{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Source event count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "replicator_source_event_count{container=\"replicator\"}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Target event count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "replicator_target_event_count{container=\"replicator\"}",
     "legendFormat": "{{target}} - {{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Avg. source processing time at source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(replicator_source_processing_latency_ms_sum[5m]) / rate(replicator_source_processing_latency_ms_count[5m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Avg target processing time per event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(replicator_target_processing_latency_ms_sum[5m]) / rate(replicator_target_processing_latency_ms_count[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Error at source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "replicator_source_error_count", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Target xform error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "replicator_target_xform_error_count",
     "legendFormat": "{{target}} - {{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "FD Usage",
   "type": "timeseries",
   "description": "Open file descriptors by the replicator instances.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "process_open_fds{container=\"replicator\"}",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Target write error count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "replicator_target_write_error_count",
     "legendFormat": "{{target}} - {{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "RSS memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{container=\"replicator\"} / 1024 / 1024",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Go GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{container=\"replicator\"}",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}} - {{quantile}}"
    }
   ]
  },
  {
   "title": "Goroutine usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "go_goroutines{container=\"replicator\"}",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "In-use Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{container=\"replicator\"} / 1024 / 1024",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "go_memstats_heap_objects{container=\"replicator\"}",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "go_threads{container=\"replicator\"}",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutine count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "go_goroutines{container=\"replicator\"}",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"replicator\"}[10m]) * 100"
    }
   ]
  }
 ]
}