{
 "title": "RW.SDN Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "query": "query_result(system_cpu_usage)" },
   {
    "name": "instance_name",
    "query": "query_result(up{job=~\"$job\"})"
   },
   {
    "name": "instance",
    "query": "query_result(up{app_kubernetes_io_instance=~\"$instance_name\"})"
   },
   { "name": "data_interval", "query": "1m,2m,5m,10m,15m,30m,1h,2h,1d" }
  ]
 },
 "panels": [
  {
   "title": "[$instance_name] [$instance] JVM uptime - seconds",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
     "legendFormat": "{{app_kubernetes_io_instance}} {{instance}} {{pod_template_hash}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$instance_name] [$instance] - Memory - Heap - Young Used & Max",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\",id=\"Eden Space\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "Max {{app_kubernetes_io_instance}} {{instance}}"
      },
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\",id=\"Eden Space\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "Used {{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] - Memory - Heap - Tenured Used & Max",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{area=\"heap\",id=\"Tenured Gen\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "Max {{app_kubernetes_io_instance}} {{instance}}"
      },
      {
       "expr": "jvm_memory_used_bytes{area=\"heap\",id=\"Tenured Gen\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "Used {{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Tenured used percentage",
     "type": "graph",
     "description": "The percentage of old gen heap used after the last GC event",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_usage_after_gc_percent{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"} * 100",
       "legendFormat": " {{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Percent of CPU time used by GC activities",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_overhead_percent{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"} * 100",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage & Threads count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$instance_name] [$instance] CPU usage",
     "type": "graph",
     "description": "The CPU usage of service instance $instance_name / $instance",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}} {{pod_template_hash}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] - Threads Count Live & Peak",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live_threads{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "Live {{app_kubernetes_io_instance}} {{instance}}"
      },
      {
       "expr": "jvm_threads_peak_threads{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "Peak {{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jetty",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$instance_name] [$instance] Jetty - 5XX response [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jetty_responses_total{status=\"5xx\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Jetty - 4XX response [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jetty_responses_total{status=\"4xx\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Jetty - 2XX response [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(jetty_responses_total{status=\"2xx\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Jetty - Current sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jetty_requests_active",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$instance_name] [$instance] Tomcat - 4XX response [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (app_kubernetes_io_instance, instance)(rate(http_server_requests_seconds_count{outcome=\"CLIENT_ERROR\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval]))",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Tomcat - 5XX response [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (app_kubernetes_io_instance, instance)(rate(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval]))",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Tomcat - 2XX response [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (app_kubernetes_io_instance,instance)(rate(http_server_requests_seconds_count{outcome=\"SUCCESS\",app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval]))",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NATS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$instance_name] [$instance] NATS - In/Out messages count [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nats_connection_msgs_in_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "In  {{app_kubernetes_io_instance}} {{instance}}"
      },
      {
       "expr": "rate(nats_connection_msgs_out_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "Out {{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] NATS - In/Out bytes count [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nats_connection_msgs_in_bytes_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "In {{app_kubernetes_io_instance}} {{instance}}"
      },
      {
       "expr": "rate(nats_connection_msgs_out_bytes_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "Out {{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] NATS reconnect [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nats_connection_reconnects_events_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$instance_name] [$instance] Kafka - Produces byte rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_outgoing_byte_rate{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "Producer {{app_kubernetes_io_instance}} {{instance}} {{client_id}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Kafka - Records sent [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_producer_record_send_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "Total  {{app_kubernetes_io_instance}} {{instance}} {{client_id}}"
      },
      {
       "expr": "rate(kafka_producer_record_error_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "Error {{app_kubernetes_io_instance}} {{instance}} {{client_id}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Kafka - Consumes byte rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_incoming_byte_rate{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "Consumer {{app_kubernetes_io_instance}} {{instance}} {{client_id}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Kafka - Producer record drop rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_buffer_exhausted_rate{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}} {{client_id}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Kafka - Consumer rebalance Total & Failed [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_consumer_coordinator_failed_rebalance_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "Failed {{app_kubernetes_io_instance}} {{instance}} {{client_id}}"
      },
      {
       "expr": "rate(kafka_consumer_coordinator_rebalance_total{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}[$data_interval])",
       "legendFormat": "Total {{app_kubernetes_io_instance}} {{instance}} {{client_id}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Kafka - Producer record retry rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_record_retry_rate{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}} {{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mongo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$instance_name] [$instance] FAILED query [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_driver_commands_seconds_count{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\",status=\"FAILED\"}[$data_interval])",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}} {{command}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Waiting for connection",
     "type": "graph",
     "description": "The current size of the wait queue for a connection from the pool",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_driver_pool_waitqueuesize{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] SUCCESS query [$data_interval]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_driver_commands_seconds_count{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\",status=\"SUCCESS\"}[$data_interval])",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}} {{command}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] MongoDb client pool size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_driver_pool_size{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}}"
      }
     ]
    },
    {
     "title": "[$instance_name] [$instance] Max MongoDb query times",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_driver_commands_seconds_max{app_kubernetes_io_instance=~\"$instance_name\",instance=~\"$instance\"}",
       "legendFormat": "{{app_kubernetes_io_instance}} {{instance}} [{{command}}]"
      }
     ]
    }
   ]
  }
 ]
}