{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdnc-artifactory.fullname" . }}-nginx
  labels:
    {{- include "sdnc-artifactory.labels" . | nindent 4 }}-nginx
  namespace: {{ include "sdnc.namespace" . }}
{{- with .Values.nginx.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
  {{- if .Values.nginx.http }}
  {{- if .Values.nginx.http.enabled }}
  - port: {{ .Values.nginx.http.externalPort }}
    targetPort: {{ .Values.nginx.http.internalPort }}
    {{- if .Values.nginx.service.nodePort }}
    nodePort: {{ .Values.nginx.service.nodePort }}
    {{- end }}
    protocol: TCP
    name: http
  {{- end }}
  {{- else }} # DEPRECATED
  - port: {{ .Values.nginx.externalPortHttp }}
    targetPort: {{ .Values.nginx.internalPortHttp }}
    protocol: TCP
    name: http
  {{- end }}
  {{- if .Values.nginx.https }}
  {{- if or .Values.nginx.https.enabled .Values.nginx.service.ssloffload }}
  - port: {{ .Values.nginx.https.externalPort }}
    {{- if .Values.nginx.service.ssloffload }}
    targetPort: {{ .Values.nginx.http.internalPort }}
    {{- else }}
    targetPort: {{ .Values.nginx.https.internalPort}}
    {{- end }}
    {{- if .Values.nginx.service.nodePort }}
    nodePort: {{ .Values.nginx.service.nodePort }}
    {{- end }}
    protocol: TCP
    name: https
  {{- end }}
  {{- else }} # DEPRECATED
  - port: {{ .Values.nginx.externalPortHttps }}
    targetPort: {{ .Values.nginx.internalPortHttps }}
    protocol: TCP
    name: https
  {{- end }}
  selector:
    {{- include "sdnc-artifactory.selectorLabels" . | nindent 4 }}-nginx
{{- end }}
