{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ template "sdnc-artifactory.fullname" . }}-nginx-certificate
  namespace: {{ include "sdnc.namespace" . }}
  labels:
    {{- include "sdnc-artifactory.labels" . | nindent 4 }}-nginx
data:
{{ ( include "artifactory.gen-certs" . ) | indent 2 }}
{{- end }}