# Copyright 2020-2021 RIFT Inc
# Copyright 2021-2022 DZS Inc
# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""
prometheusfullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 489

containerSecurityContext:
  runAsUser: 489
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  #
replicator:
  image:
    repository: rt.cloud.dzsi.local/docker/rw-replicator
    tag: "2.7"
    pullPolicy: IfNotPresent

enableVolumePermissions: false

prometheus:
  image:
    repository: rt.cloud.dzsi.local/quay.io/prometheus/prometheus
    tag: "v2.40.7"
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  capabilities: []
  service:
    type: ClusterIP
  ports:
    rwprom: 9090
  coreDir: null

  busybox:
    image:
      repository: rt.cloud.dzsi.local/docker-hub/busybox
      pullPolicy: IfNotPresent

  configWatch:
    image:
      repository: rt.cloud.dzsi.local/docker-hub/weaveworks/watch
      tag: "master-5b2a6e5"
      pullPolicy: IfNotPresent

  pushGateway:
    image:
      repository: rt.cloud.dzsi.local/quay.io/prometheus/pushgateway
      tag: "v1.4.3"
      pullPolicy: IfNotPresent
    port: 9091 # This affects only the cluster port
  runAsUser: 1024

# Hostname or IP address through which launchpad can be externally accessed
# This value is mandatory except if service type is "LoadBalancer"
externalAddress: null

imagePullSecrets: []

prometheusStorage:
  storageClassName: null
  capacity: 80Gi
  localStore: {}
  manual: {}
  nfs: {}
