apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdnc-artifactory-postgresql.fullname" . }}
  labels:
    {{- include "sdnc-artifactory-postgresql.labels" . | nindent 4 }}
  namespace: {{ include "sdnc.namespace" . }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    {{- include "sdnc-artifactory-postgresql.selectorLabels" . | nindent 4 }}
