# Copyright 2021-2022 DZS Inc
# Copyright 2020-2021 RIFT Inc
{{- if .Values.global.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.name }}
  labels:
    {{- include "launchpad.labels" . | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.global.namespace.name }}
  name: rift-edit
rules:
# core group edit permissions
- apiGroups: [""]
  resources: ["pods","configmaps", "secrets", "services"]
  verbs: ["get", "watch", "list", "create", "patch", "update", "delete", "deletecollection"]
# core group logs/status read permission
- apiGroups: [""]
  resources: ["pods/log","pods/status"]
  verbs: ["get", "watch", "list"]
# core group for pod/exec permission
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
# apps group edit permission
- apiGroups: ["apps"]
  resources: ["daemonsets","deployments", "replicasets", "statefulsets"]
  verbs: ["get", "watch", "list", "create", "patch", "update", "delete", "deletecollection"]
{{- if .Values.global.install.aeo }}
---
# For providing configuration to AEO pods
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "aeo.namespace" . }}
  name: aeo-config
rules:
# core group edit permissions
- apiGroups: [""]
  resources: ["pods","configmaps", "secrets", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "patch", "update", "delete"]
# aeo group logs/status read permission
- apiGroups: [""]
  resources: ["pods/log","pods/status"]
  verbs: ["get", "watch", "list"]
{{- end }}
---
# Role binding for the default role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.global.namespace.name }}-role-bind
  namespace: {{ .Values.global.namespace.name }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.global.namespace.name }}
roleRef:
  kind: Role
  name: rift-edit
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.global.install.aeo }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aeo.namespace" . }}-role-bind
  namespace: {{ include "aeo.namespace" . }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.global.namespace.name }}
roleRef:
  kind: Role
  name: aeo-config
  apiGroup: rbac.authorization.k8s.io
{{- end }}